# Generated by Django 4.0.6 on 2023-12-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_image_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
